### ISSUE TITLE
offset parameter  in renewalCount function

### ISSUE THREAD

**Issue by HANANEMIFTAH** [GeoBosh/Countr#4]
I have a database and I would like to use the gamma and weibull distribution to model the number of events that occurred during different time intervals.

I have found the countr package to meet my requirements perfectly. I made two scenarios, in the first one I model the number of events according to some covariates without using the offset parameter. In the second scenario I used the offset parameter. Comparing summary of the two scenarios, the result is identical.  This result does not match my expectations and I do not know why?

Regarding the Countr package, I would like to know if the offset parameter is implemented in the renewalCount function ?

I am a new user of rstudio.

Thanks

**Comment by GeoBosh** [comment]
Currently the `offset` argument is ignored, as documented in `renewalCount()`:
```
...
offset - optional numeric vector with an a priori known component 
            to be included in the linear predictor of the count model. 
            Currently not used.
...
```
